using Npgsql;
using Raffaello.Core.Domain;
using static Raffaello.Server.Data.PgMap;

namespace Raffaello.Server.Data;

/// <summary>
/// Creates and upgrades the database. Two layers:
/// 1. numbered migrations for the server's own tables (audit, presence, users, documents, approvals ...), applied once each
///    and recorded in "__schema_migrations";
/// 2. entity tables generated from the registered Core entity types, created / extended additively (new columns only, never
///    dropped) on every start - the same rule the SQLite store follows, so a new property in Core needs no hand-written migration.
/// Runs under an advisory lock so two server processes never migrate at the same time.
/// </summary>
public static class PgSchema
{
    public sealed record Migration(int Version, string Name, string Sql);

    public static readonly IReadOnlyList<Migration> Migrations = new[]
    {
        new Migration(1, "system tables", """
            CREATE TABLE IF NOT EXISTS "AuditLog" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "At" timestamp NOT NULL, "User" text, "Machine" text, "TableName" text, "RowId" bigint,
                "Action" text, "Summary" text, "Changes" text, "OldJson" text, "NewJson" text);
            CREATE INDEX IF NOT EXISTS "IX_AuditLog_At" ON "AuditLog" ("At");
            CREATE INDEX IF NOT EXISTS "IX_AuditLog_Row" ON "AuditLog" ("TableName", "RowId");
            CREATE TABLE IF NOT EXISTS "Presence" ("Machine" text NOT NULL, "User" text NOT NULL, "Screen" text, "LastSeen" timestamp,
                PRIMARY KEY ("Machine", "User"));
            CREATE TABLE IF NOT EXISTS "Meta" ("Key" text PRIMARY KEY, "Value" text);
            CREATE TABLE IF NOT EXISTS "__table_versions" ("TableName" text PRIMARY KEY, "Version" bigint NOT NULL);
            CREATE TABLE IF NOT EXISTS "__requests" ("RequestId" uuid PRIMARY KEY, "At" timestamp NOT NULL, "User" text, "Response" text NOT NULL);
            CREATE TABLE IF NOT EXISTS "Users" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserName" text NOT NULL, "DisplayName" text NOT NULL DEFAULT '', "Role" text NOT NULL,
                "PasswordHash" text, "WindowsAccount" text NOT NULL DEFAULT '', "Active" boolean NOT NULL DEFAULT true,
                "CreatedAt" timestamp NOT NULL, "LastLoginAt" timestamp);
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_UserName" ON "Users" (lower("UserName"));
            CREATE TABLE IF NOT EXISTS "Sessions" ("TokenHash" text PRIMARY KEY, "UserId" bigint NOT NULL, "CreatedAt" timestamp NOT NULL,
                "ExpiresAt" timestamp NOT NULL, "Machine" text);
            CREATE TABLE IF NOT EXISTS "Documents" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FileName" text NOT NULL, "ContentType" text NOT NULL DEFAULT '', "Size" bigint NOT NULL, "Sha256" text NOT NULL,
                "RelPath" text NOT NULL, "Category" text NOT NULL DEFAULT '', "LinkedTable" text NOT NULL DEFAULT '', "LinkedId" bigint NOT NULL DEFAULT 0,
                "UploadedBy" text NOT NULL, "UploadedAt" timestamp NOT NULL);
            CREATE INDEX IF NOT EXISTS "IX_Documents_Sha" ON "Documents" ("Sha256");
            CREATE INDEX IF NOT EXISTS "IX_Documents_Link" ON "Documents" ("LinkedTable", "LinkedId");
            CREATE TABLE IF NOT EXISTS "ApprovalStamps" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TableName" text NOT NULL, "RowId" bigint NOT NULL, "Stage" text NOT NULL, "FromStatus" text NOT NULL DEFAULT '',
                "ToStatus" text NOT NULL DEFAULT '', "RowVersion" bigint NOT NULL, "By" text NOT NULL, "Role" text NOT NULL DEFAULT '',
                "At" timestamp NOT NULL, "Note" text NOT NULL DEFAULT '');
            CREATE INDEX IF NOT EXISTS "IX_ApprovalStamps_Row" ON "ApprovalStamps" ("TableName", "RowId");
            """),
    };

    public static void Migrate(NpgsqlDataSource ds)
    {
        EntityRegistry.EnsureInitialized();
        using var c = ds.OpenConnection();
        using (var lockCmd = new NpgsqlCommand("SELECT pg_advisory_lock(7101975)", c)) lockCmd.ExecuteNonQuery();
        try
        {
            using (var cmd = new NpgsqlCommand("""CREATE TABLE IF NOT EXISTS "__schema_migrations" ("Version" integer PRIMARY KEY, "Name" text, "AppliedAt" timestamp NOT NULL)""", c))
                cmd.ExecuteNonQuery();
            var applied = new HashSet<int>();
            using (var cmd = new NpgsqlCommand("""SELECT "Version" FROM "__schema_migrations" """, c))
            using (var r = cmd.ExecuteReader())
                while (r.Read()) applied.Add(r.GetInt32(0));

            foreach (var m in Migrations.Where(m => !applied.Contains(m.Version)).OrderBy(m => m.Version))
            {
                using var tx = c.BeginTransaction();
                var t = new PgTx(c, tx);
                t.Exec(m.Sql);
                t.Exec("""INSERT INTO "__schema_migrations" ("Version", "Name", "AppliedAt") VALUES (@v, @n, @a)""", ("v", m.Version), ("n", m.Name), ("a", DateTime.Now));
                tx.Commit();
            }

            using (var tx = c.BeginTransaction())
            {
                var t = new PgTx(c, tx);
                foreach (var type in EntityRegistry.All) EnsureEntityTable(t, type);
                EnsureIndexes(t);
                tx.Commit();
            }
        }
        finally
        {
            using var unlock = new NpgsqlCommand("SELECT pg_advisory_unlock(7101975)", c);
            unlock.ExecuteNonQuery();
        }
    }

    public static void EnsureEntityTable(PgTx t, Type type)
    {
        var table = EntityRegistry.TableOf(type);
        var props = EntityRegistry.Props(type);
        var cols = props.Where(p => p.Name != nameof(Entity.Id)).Select(p => $"{Q(p.Name)} {SqlType(p.PropertyType)}");
        t.Exec($"CREATE TABLE IF NOT EXISTS {Q(table)} ({Q("Id")} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, {string.Join(", ", cols)})");
        var existing = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        using (var cmd = t.Command("SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = @t", ("t", table)))
        using (var r = cmd.ExecuteReader())
            while (r.Read()) existing.Add(r.GetString(0));
        foreach (var p in props.Where(p => !existing.Contains(p.Name)))
            t.Exec($"ALTER TABLE {Q(table)} ADD COLUMN {Q(p.Name)} {SqlType(p.PropertyType)}");
    }

    private static void EnsureIndexes(PgTx t)
    {
        t.Exec("""CREATE INDEX IF NOT EXISTS "IX_WirLines_Line" ON "WirLines" ("LineId")""");
        t.Exec("""CREATE INDEX IF NOT EXISTS "IX_InvoiceLines_Line" ON "InvoiceLines" ("LineId")""");
        t.Exec("""CREATE INDEX IF NOT EXISTS "IX_Allocations_Line" ON "Allocations" ("LineId")""");
        t.Exec("""CREATE INDEX IF NOT EXISTS "IX_SubInvoiceLines_Inv" ON "SubInvoiceLines" ("SubInvoiceId")""");
        // the ledger key (room | stage | item) used by the remaining check
        t.Exec("""CREATE INDEX IF NOT EXISTS "IX_ClaimLines_Key" ON "ClaimLines" (upper(btrim("Room")), upper(btrim("Stage")), upper(btrim("Item")))""");
        t.Exec("""CREATE INDEX IF NOT EXISTS "IX_RoomQtys_Key" ON "RoomQtys" (upper(btrim("Room")), upper(btrim("Stage")), upper(btrim("Item")))""");
    }

    /// <summary>Moves an identity sequence past the highest id (after rows were inserted with explicit ids).</summary>
    public static void ResetIdentity(PgTx t, string table) =>
        t.Exec($"SELECT setval(pg_get_serial_sequence(@t, 'Id'), (SELECT COALESCE(MAX({Q("Id")}), 0) + 1 FROM {Q(table)}), false)", ("t", Q(table)));
}
