#!/usr/bin/env python3
"""Builds src/Raffaello.Core/Localization/Strings.resx (English) and Strings.ar.resx (Arabic) from the two tables next to them:

  strings.keys.tsv  key <TAB> English <TAB> Arabic      (stable keys used in code / XAML: Nav_Dashboard, Btn_Save ...)
  strings.ui.tsv    English <TAB> Arabic                (literal texts still written in XAML; key = Ui_<slug>)

Edit the tables, run  python3 tools/localization/build_strings.py  and commit the regenerated .resx files.
With --coverage it also reports how many literal XAML texts of src/Raffaello.App have an Arabic translation.
"""
import html
import os
import re
import sys
from xml.sax.saxutils import escape

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LOC = os.path.join(ROOT, "src", "Raffaello.Core", "Localization")

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- generated by tools/localization/build_strings.py from strings.keys.tsv and strings.ui.tsv - edit the tables, not this file -->
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def fold(s):
    return " ".join(s.split()).upper()


def slug(en):
    words = re.findall(r"[A-Za-z0-9]+", en.upper())
    s = "_".join(words)[:48].strip("_")
    return "Ui_" + (s or "X")


def read_tables():
    rows = []  # (key, en, ar)
    seen_keys = set()
    with open(os.path.join(LOC, "strings.keys.tsv"), encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            key, en, ar = (line.split("\t") + ["", ""])[:3]
            rows.append((key, en, ar))
            seen_keys.add(key)
    folded = {fold(en) for _, en, _ in rows}
    with open(os.path.join(LOC, "strings.ui.tsv"), encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            en, ar = (line.split("\t") + [""])[:2]
            if fold(en) in folded:
                continue
            folded.add(fold(en))
            key = slug(en)
            n = 2
            while key in seen_keys:
                key = f"{slug(en)}_{n}"
                n += 1
            seen_keys.add(key)
            rows.append((key, en, ar))
    return rows


def write(path, items):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        for key, value in items:
            f.write(f'  <data name="{escape(key, {chr(34): "&quot;"})}" xml:space="preserve"><value>{escape(value)}</value></data>\n')
        f.write("</root>\n")


NEUTRAL = re.compile(r"^[\W\d_]*$|^(?:[A-Z0-9]{1,4}[.%]?|PDF|ZIP|EXCEL|EMT|WIR|MIR|DN|PO|QS|INV|BOQ|SHA-256|PYTHON|RAFFAELLO|Raffaello|Ctrl\+.*|CTRL.*|R A F F A E L L O)$")


def coverage(rows):
    app = os.path.join(ROOT, "src", "Raffaello.App", "Views")
    texts = set()
    for d, _, files in os.walk(app):
        for fn in files:
            if fn.endswith(".xaml"):
                with open(os.path.join(d, fn), encoding="utf-8") as f:
                    for m in re.finditer(r'\b(?:Text|Content|Header|ToolTip|Title)="([^"{][^"]*)"', f.read()):
                        texts.add(html.unescape(m.group(1)).strip())
    have = {fold(en) for _, en, ar in rows if ar}
    real = [t for t in texts if t and not NEUTRAL.match(t.strip())]
    covered = [t for t in real if fold(t) in have]
    missing = sorted(set(real) - set(covered))
    print(f"literal XAML texts: {len(texts)}; language-neutral (codes, numbers, punctuation): {len(texts) - len(real)}")
    print(f"translatable: {len(real)}; with Arabic: {len(covered)} ({100.0 * len(covered) / max(1, len(real)):.1f} %)")
    keys = [r for r in rows]
    print(f"table entries: {len(keys)}; with Arabic: {sum(1 for r in keys if r[2])}")
    if "--missing" in sys.argv:
        for t in missing:
            print("  MISSING:", t)


def main():
    rows = read_tables()
    write(os.path.join(LOC, "Strings.resx"), [(k, en) for k, en, _ in rows])
    write(os.path.join(LOC, "Strings.ar.resx"), [(k, ar) for k, _, ar in rows if ar])
    print(f"{len(rows)} strings written")
    if "--coverage" in sys.argv:
        coverage(rows)


if __name__ == "__main__":
    main()
