using System.Globalization;
using System.Security.Cryptography;
using Npgsql;
using Raffaello.Core.Portal;
using Raffaello.Core.Remote;
using Raffaello.Server.Auth;
using Raffaello.Server.Data;

namespace Raffaello.Server.Portal;

public sealed class PortalAccountRow
{
    public long Id { get; set; }
    public string UserName { get; set; } = "";
    public string DisplayName { get; set; } = "";
    public string Company { get; set; } = "";
    public string Language { get; set; } = "en";
    public string PasswordHash { get; set; } = "";
    public bool Active { get; set; } = true;
    public DateTime CreatedAt { get; set; }
    public string CreatedBy { get; set; } = "";
    public DateTime? LastLoginAt { get; set; }

    public PortalAccountDto ToDto() => new()
    {
        Id = Id, UserName = UserName, DisplayName = DisplayName, Company = Company, Language = Language, Active = Active, LastLoginAt = LastLoginAt, CreatedBy = CreatedBy,
    };
}

/// <summary>
/// Subcontractor accounts of the portal. Kept apart from the app's Users / Sessions on purpose: a portal token is never
/// accepted by the internal API (the internal token handler does not know it), and an app token is never accepted by the
/// portal. Each account belongs to exactly one company; the server filters every answer by it.
/// </summary>
public sealed class PortalAccounts
{
    private readonly NpgsqlDataSource _ds;
    public TimeSpan TokenLifetime { get; init; } = TimeSpan.FromHours(12);
    public int BcryptWorkFactor { get; init; } = 11;

    public PortalAccounts(NpgsqlDataSource ds) => _ds = ds;

    public const string Schema = """
        CREATE TABLE IF NOT EXISTS "PortalAccounts" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserName" text NOT NULL, "DisplayName" text NOT NULL DEFAULT '', "Company" text NOT NULL, "Language" text NOT NULL DEFAULT 'en',
            "PasswordHash" text NOT NULL, "Active" boolean NOT NULL DEFAULT true, "CreatedAt" timestamp NOT NULL, "CreatedBy" text NOT NULL DEFAULT '',
            "LastLoginAt" timestamp);
        CREATE UNIQUE INDEX IF NOT EXISTS "UX_PortalAccounts_UserName" ON "PortalAccounts" (lower("UserName"));
        CREATE TABLE IF NOT EXISTS "PortalSessions" ("TokenHash" text PRIMARY KEY, "AccountId" bigint NOT NULL, "CreatedAt" timestamp NOT NULL,
            "ExpiresAt" timestamp NOT NULL, "Address" text NOT NULL DEFAULT '');
        """;

    public void EnsureSchema()
    {
        using var c = _ds.OpenConnection();
        using var tx = c.BeginTransaction();
        var p = new PgTx(c, tx);
        p.Lock("portal-schema");
        p.Exec(Schema);
        tx.Commit();
    }

    private PgTx Open(out NpgsqlConnection c) { c = _ds.OpenConnection(); return new PgTx(c, null); }

    public List<PortalAccountRow> All()
    {
        var p = Open(out var c); using (c) return p.Query<PortalAccountRow>("""SELECT * FROM "PortalAccounts" ORDER BY "Company", "UserName" """);
    }

    public PortalAccountRow? Find(string userName)
    {
        var p = Open(out var c);
        using (c) return p.Query<PortalAccountRow>("""SELECT * FROM "PortalAccounts" WHERE lower("UserName") = lower(@u)""", ("u", userName.Trim())).FirstOrDefault();
    }

    public PortalAccountRow? FindById(long id)
    {
        var p = Open(out var c);
        using (c) return p.Query<PortalAccountRow>("""SELECT * FROM "PortalAccounts" WHERE "Id" = @id""", ("id", id)).FirstOrDefault();
    }

    public PortalAccountRow Create(PortalAccountDto dto, string createdBy)
    {
        var user = (dto.UserName ?? "").Trim();
        if (user.Length < 3 || user.Any(ch => char.IsWhiteSpace(ch) || char.IsControl(ch))) throw new WriteRejectedException(400, ErrorCodes.BadRequest, "User name: at least 3 characters, no spaces.");
        var company = (dto.Company ?? "").Trim().ToUpperInvariant();
        if (company.Length == 0) throw new WriteRejectedException(400, ErrorCodes.BadRequest, "Every portal account belongs to a company (the subcontractor name used in the ledger).");
        ValidatePassword(dto.Password);
        if (Find(user) != null) throw new WriteRejectedException(409, ErrorCodes.Conflict, $"Portal user {user} already exists.");
        var p = Open(out var c);
        using (c)
        {
            var id = Convert.ToInt64(p.Scalar("""
                INSERT INTO "PortalAccounts" ("UserName", "DisplayName", "Company", "Language", "PasswordHash", "Active", "CreatedAt", "CreatedBy")
                VALUES (@u, @d, @c, @l, @h, true, @at, @by) RETURNING "Id"
                """, ("u", user), ("d", string.IsNullOrWhiteSpace(dto.DisplayName) ? user : dto.DisplayName.Trim()), ("c", company), ("l", Lang(dto.Language)),
                ("h", BCrypt.Net.BCrypt.HashPassword(dto.Password, BcryptWorkFactor)), ("at", DateTime.Now), ("by", createdBy)), CultureInfo.InvariantCulture);
            return FindById(id)!;
        }
    }

    public PortalAccountRow Update(long id, PortalAccountDto dto)
    {
        var a = FindById(id) ?? throw new WriteRejectedException(404, ErrorCodes.NotFound, $"Portal account #{id} not found.");
        var hash = a.PasswordHash;
        if (!string.IsNullOrEmpty(dto.Password)) { ValidatePassword(dto.Password); hash = BCrypt.Net.BCrypt.HashPassword(dto.Password, BcryptWorkFactor); }
        var company = string.IsNullOrWhiteSpace(dto.Company) ? a.Company : dto.Company.Trim().ToUpperInvariant();
        var p = Open(out var c);
        using (c)
        {
            p.Exec("""
                UPDATE "PortalAccounts" SET "DisplayName" = @d, "Company" = @c, "Language" = @l, "PasswordHash" = @h, "Active" = @a WHERE "Id" = @id
                """, ("d", string.IsNullOrWhiteSpace(dto.DisplayName) ? a.DisplayName : dto.DisplayName.Trim()), ("c", company), ("l", Lang(dto.Language ?? a.Language)),
                ("h", hash), ("a", dto.Active), ("id", id));
            // a changed password, company or a disabled account ends every open session
            if (!dto.Active || hash != a.PasswordHash || company != a.Company) p.Exec("""DELETE FROM "PortalSessions" WHERE "AccountId" = @id""", ("id", id));
        }
        return FindById(id)!;
    }

    private static string Lang(string? l) => string.Equals(l, "ar", StringComparison.OrdinalIgnoreCase) ? "ar" : "en";

    public static void ValidatePassword(string? password)
    {
        if (string.IsNullOrEmpty(password) || password.Length < 10 || !password.Any(char.IsLetter) || !password.Any(char.IsDigit))
            throw new WriteRejectedException(400, ErrorCodes.BadRequest, "Portal passwords need at least 10 characters with letters and digits.");
    }

    public PortalLoginResponse? Login(string userName, string password, string address)
    {
        var a = Find(userName ?? "");
        if (a is null || !a.Active || !BCrypt.Net.BCrypt.Verify(password ?? "", a.PasswordHash))
        {
            if (a is null) BCrypt.Net.BCrypt.HashPassword("timing-equaliser", 4);
            return null;
        }
        var token = "p_" + Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)).TrimEnd('=').Replace('+', '-').Replace('/', '_');
        var expires = DateTime.Now.Add(TokenLifetime);
        var p = Open(out var c);
        using (c)
        {
            p.Exec("""INSERT INTO "PortalSessions" ("TokenHash", "AccountId", "CreatedAt", "ExpiresAt", "Address") VALUES (@h, @a, @c, @e, @ad)""",
                ("h", UserStore.Hash(token)), ("a", a.Id), ("c", DateTime.Now), ("e", expires), ("ad", address ?? ""));
            p.Exec("""UPDATE "PortalAccounts" SET "LastLoginAt" = @at WHERE "Id" = @id""", ("at", DateTime.Now), ("id", a.Id));
            p.Exec("""DELETE FROM "PortalSessions" WHERE "ExpiresAt" < @now""", ("now", DateTime.Now));
        }
        return new PortalLoginResponse { Token = token, UserName = a.UserName, DisplayName = a.DisplayName, Company = a.Company, Language = a.Language, ExpiresAt = expires };
    }

    public PortalAccountRow? Validate(string token)
    {
        if (string.IsNullOrEmpty(token) || !token.StartsWith("p_", StringComparison.Ordinal)) return null;
        var p = Open(out var c);
        using (c)
            return p.Query<PortalAccountRow>("""
                SELECT a.* FROM "PortalSessions" s JOIN "PortalAccounts" a ON a."Id" = s."AccountId"
                WHERE s."TokenHash" = @h AND s."ExpiresAt" > @now AND a."Active"
                """, ("h", UserStore.Hash(token)), ("now", DateTime.Now)).FirstOrDefault();
    }

    public void Revoke(string token)
    {
        var p = Open(out var c);
        using (c) p.Exec("""DELETE FROM "PortalSessions" WHERE "TokenHash" = @h""", ("h", UserStore.Hash(token)));
    }
}
